### ISSUE TITLE
Could not find compiled dynamic library error. 

### ISSUE THREAD

**Issue by amqndin** [vyfor/cord.nvim#104]
### Description

when i log into neovim it gives me this error
```
[cord.nvim] Could not find the compiled dynamic library at: C:/Users/User/AppData/Local/nvim-data/lazy/cord.nvim/cord.dll. Please re-run the build script
```

### Operating system

Windows 10 Pro 22H2

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

### Steps to reproduce

1. `nvim -nu ./init.lua`
2. thats it you got error'd

### Expected behavior

for rpc ro work

### Actual behavior

error and rpc doesnt appear

### Minimal configuration

```Lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
	if vim.v.shell_error ~= 0 then
		vim.api.nvim_echo({
			{ "Failed to clone lazy.nvim:\n", "ErrorMsg" },
			{ out, "WarningMsg" },
			{ "\nPress any key to exit..." },
		}, true, {})
		vim.fn.getchar()
		os.exit(1)
	end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
	spec = {
		-- add your plugins here
		{
			"vyfor/cord.nvim",
			build = ".\\build",
			event = "VeryLazy",
			opts = {},
		},
	},
	-- Configure any other settings here. See the documentation for more details.
	-- colorscheme that will be used when installing plugins.
	install = { colorscheme = { "habamax" } },
	-- automatically check for plugin updates
	checker = { enabled = true },
})
```

**Comment by vyfor** [comment]
Hey! Can you please try to reinstall the plugin, and if that doesn't help, try manually building it and see if there are any build errors:
```bat
cd %LOCALAPPDATA%\nvim-data\lazy\cord.nvim && call build.bat
```

**Comment by amqndin** [comment]
where should the build appear? 
```
> call build.bat

rustc --crate-type=cdylib -C opt-level=3 -C panic=abort -C lto=fat -o cord src/lib.r
```
this is what i got after running call build.bat in that directory

**Comment by vyfor** [comment]
That should create a file named `cord` in the same directory. `cord.nvim` will then append a platform-specific file extension (in your case, `.dll`).

**Comment by amqndin** [comment]
> Is it able to locate the file now?

yes, its working! thank you. though i wonder why it would only work after i manually built

**Comment by vyfor** [comment]
I suppose you initially used `build = "./build"` in lazy, which fails to locate build.bat in the command prompt (default shell on neovim, though it works in powershell). And after changing it to `.\\build`, lazy won’t rebuild unless you reinstall or update the plugin, so either that or manual build.
