### ISSUE TITLE
Added Fuzzy Finder

### ISSUE THREAD

**Issue by ryoppippi** [vyfor/cord.nvim#108]
### Description

I'd love to add fuzzy finder support, including
- [ddu.vim](https://github.com/Shougo/ddu.vim)
- [Telescope](https://github.com/nvim-telescope/telescope.nvim)
- [fzf.nvim](https://github.com/junegunn/fzf.vim)
- [mini.fuzzy](https://github.com/echasnovski/mini.fuzzy)

**Comment by vyfor** [comment]
Hey, I’d rather categorize these under file browsers, as they’re somewhat related.
