### ISSUE TITLE
Quarto support

### ISSUE THREAD

**Issue by PCesteban** [vyfor/cord.nvim#109]
### Description

I personally use quarto with neovim, would be nice to have the icon, the files are .qmd and quarto has a plugin for neovim as well, it should be easy to implement. For your reference: https://quarto.org/docs/get-started/hello/neovim.html

**Comment by vyfor** [comment]
icon proposal:
![image](https://github.com/user-attachments/assets/864945a1-0d80-422e-bcec-eb7805704d76)
![image](https://github.com/user-attachments/assets/704fde37-1f1c-43e7-959b-d321b4991aec)

**Comment by PCesteban** [comment]
Perfect!

**Comment by vyfor** [comment]
@PCesteban, it's done, thanks! My bad for delaying this, I had to get my computer repaired.
