### ISSUE TITLE
Workspace visible in discord mobile app while disabled

### ISSUE THREAD

**Issue by PCesteban** [vyfor/cord.nvim#115]
### Description

I have workspace disabled as it is mentioned in the README, with an empty string, it works for discord desktop, but I can see the View repository button in the mobile app and it redirects to the repo.

### Operating system

Manjaro latest

### Neovim version

```markdown
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info
```

### Steps to reproduce

- Disable workspace
- open a file in a repo
- check your status in the discord mobile app

![image](https://github.com/user-attachments/assets/47cf792d-1ed0-4fcc-8b95-f8cf177cb467)

### Expected behavior

Should not show the view repository button since workspace is disabled.

### Minimal configuration

```Lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable',
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'vyfor/cord.nvim',
    build = './build',
    opts = {},
  },
}, {})
```

**Comment by vyfor** [comment]
`text.workspace = ''` only disables the text used for workspace name. To disable the repository button do one of the two:
```lua
display.show_repository = false
-- or
buttons = {}
```

> it works for discord desktop, but I can see the View repository button in the mobile app

It is also visible on desktop, just not to you. See https://github.com/vyfor/cord.nvim/wiki/Troubleshooting#no-buttons-are-shown-in-the-rich-presence

**Comment by PCesteban** [comment]
Oh, I see. Sorry for the issue. Thanks !
