### ISSUE TITLE
Add Haxe

### ISSUE THREAD

**Issue by gedon76** [vyfor/cord.nvim#125]
### Description

Haxe is cool, it's a shame it's not here.

https://haxe.org/

**Comment by vyfor** [comment]
icon proposal:
![haxe](https://github.com/user-attachments/assets/b53ebf58-e78f-4d98-b356-f89a17543c0f)
![haxe_ss](https://github.com/user-attachments/assets/0188b658-9f3a-4d56-9c41-2254afa2b9b4)

**Comment by gedon76** [comment]
looks awesome

**Comment by gedon76** [comment]
hxml for compiler config

**Comment by vyfor** [comment]
added, thanks!
