### ISSUE TITLE
provide a way to reset on exit of idle, with `reset_on_change = false`

### ISSUE THREAD

**Issue by TheButlah** [vyfor/cord.nvim#127]
### Description

I often idle for long periods of time when editing neovim and would like the timer to only reflect time when I'm not idled. I figured that I could use `reset_on_idle` for this. I expected that when entering the idle phase, the timer will reset to 0. This matches the current behavior. However, I also thought that when *exiting* idle, the timer would reset to 0 as well. This however is not the case.

To get that behavior, I have to set `reset_on_change`, but thats not actually what I want. I would like to keep the timer counting for the entire time I'm actively editing code, not reset it when I navigate to a different file.

I'd like to request that `reset_on_idle` be changed semantically to mean "reset on entry or exit to idle state" rather than just "reset on entry to idle state". Alternatively, another config option could be introduced to separately configure the "reset on exit of idle state".

**Comment by vyfor** [comment]
I've been thinking of providing a separate field for that, but it doesn’t feel right. Adjusting `reset_on_idle` behavior makes more sense imho.

**Comment by TheButlah** [comment]
Just tested `05f10f6`, doesn't seem fixed

**Comment by vyfor** [comment]
@TheButlah I’m not sure why it wouldn’t work

https://github.com/user-attachments/assets/7f2b559d-d3fe-4f4d-8437-043f06bc2c1a

**Comment by TheButlah** [comment]
https://github.com/user-attachments/assets/9afb566e-ae4d-495b-b628-e24bba4fb2f5

**Comment by vyfor** [comment]
Can you try reinstalling the plugin?

**Comment by vyfor** [comment]
Pushed a fix to master, can you try it?

**Comment by TheButlah** [comment]
deleted .cache, .local, reinstalled, rebuilt. same issue.

https://github.com/user-attachments/assets/33ca2d78-1b55-47bf-b93f-e62611970528

**Comment by vyfor** [comment]
Hmm, after taking a closer look, I noticed that [these lines](https://github.com/vyfor/cord.nvim/blob/f2747392fba9a43ab20f542b2a07cb26a4f191ae/lua/cord.lua#L395C3-L398C6) might be resetting the idle indicator too soon, which could explain why it isn’t being the time being [reset](https://github.com/vyfor/cord.nvim/blob/f2747392fba9a43ab20f542b2a07cb26a4f191ae/lua/cord.lua#L222C43-L226C8) properly. I'll fix the implementation and get back to you.

**Comment by vyfor** [comment]
I've implemented all the necessary stuff on the `fix/reset_on_idle` branch. The terminal I was using doesn't seem to support focus events, which is likely why it seemed to work for me initially. I tested the changes in WezTerm, and hopefully, everything should work perfectly now.

**Comment by TheButlah** [comment]
It works 🥳

**Comment by vyfor** [comment]
Great! Thanks for bearing with me 😅
