### ISSUE TITLE
Vesktop Flatpak support

### ISSUE THREAD

**Issue by StayBlue** [vyfor/cord.nvim#137]
### Description

Vesktop (at least the Flatpak version) doesn't seem to be supported, as the pipe path seems to hard-coded to look for Discord specifically.

This was a bit confusing as the command to find if the pipe exists in the Troubleshooting guide found it, but the RPC plugin didn't.

### Operating system

Fedora 41

### Neovim version

```markdown
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189
```

### Steps to reproduce

1. Download the Flatpak version of Vesktop.
2. Ensure Rich Presence support is enabled under Vencord > Vesktop Settings > Miscellaneous.
3. Launch Neovim with cord installed

### Expected behavior

The connection to the pipe.is established.

### Actual behavior

The connection times out after sixty seconds.

### Minimal configuration

```Lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable',
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'vyfor/cord.nvim',
    build = './build',
    opts = {},
  },
}, {})
```

**Comment by StayBlue** [comment]
Testing out the `client-server` branch, it still doesn't seem to be able to find the pipe. I installed it following the instructions [here](https://github.com/vyfor/cord.nvim/issues/133#issuecomment-2512333697).

**Comment by vyfor** [comment]
Hello, it looks like the custom client exposes the pipe under a different path. You should create a symlink from `$XDG_RUNTIME_DIR/discord-ipc-0` to the correct path. In my case, it was in `/run/user/1000/.flatpak/dev.vencord.Vesktop/xdg-run/discord-ipc-0`. The [ArchWiki](https://wiki.archlinux.org/title/Discord) has a more detailed guide on this.

**Comment by StayBlue** [comment]
I had followed the instructions [here](https://github.com/flathub/dev.vencord.Vesktop?tab=readme-ov-file#native-applications) before opening the issue, but it seems like I needed to restart before it had any effect. Apologies for the mistake!

I hope this issue helps others who have the same problem as I did.
