### ISSUE TITLE
Cuda files

### ISSUE THREAD

**Issue by PCesteban** [vyfor/cord.nvim#139]
### Description

an icon for .cu file extension, this is how my neovim recognize it:
![image](https://github.com/user-attachments/assets/888f1a8b-3973-46e5-8e18-8962ae603e66)

**Comment by vyfor** [comment]
icon proposal:
![image](https://github.com/user-attachments/assets/f0afb556-91e4-4b90-84cf-f022d586bebf)
![nvidia](https://github.com/user-attachments/assets/8dc48ae9-91a9-4a90-a90e-6e2743e4b1f5)

**Comment by PCesteban** [comment]
Looks great!
