### ISSUE TITLE
Unable to run on NixOS

### ISSUE THREAD

**Issue by DockterTeagle** [vyfor/cord.nvim#144]
### Description

after updating to the altest version, I get this error:
```
[cord.nvim] Could not start dynamically linked executable: /home/cdockter/.local/share/nvim/cord/bin/cord
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

### Operating system

NixoS

### Neovim version

```markdown
NVIM v0.11.0-nightly+c51bf5a
Build type: Release
LuaJIT 2.1.1713773202
```

### Steps to reproduce

just try to install cord.nvim on latest branch(the rewrite) on nixos

### Expected behavior

to be able to run

### Actual behavior

error occurs, doesnt run but on the brightside doesnt break the entire config, consider blink.cmp's build command as it works flawlessly

### Minimal configuration

```Lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable',
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  
	{
		"vyfor/cord.nvim",
		branch = "client-server",
		build = ":Cord fetch",
		event = "VeryLazy",
		opts = {},
	},

}, {})
```

**Comment by vyfor** [comment]
Hey! I'm sorry that you're experiencing this. I'll change the CI to build against musl which should statically link everything and hopefully resolve this issue. I'm unable to do this immediately, but once I'm back at my computer and make the change, I'll let you know.

**Comment by vyfor** [comment]
Please update to the latest version of the plugin and run `:Cord fetch`.

**Comment by DockterTeagle** [comment]
it works now thank you
