### ISSUE TITLE
Failed to spawn process: EACCES: permission denied

### ISSUE THREAD

**Issue by me11203sci** [vyfor/cord.nvim#146]
### Description

The error described in the title occurs upon opening neovim and status is not detected in Discord. Setting `log_level="trace"` and calling `:message` yields no further information.

### Operating system

Manjaro 6.11.11-1-MANJARO

### Neovim version

```markdown
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260
Run "nvim -V1 -v" for more info
```

### Steps to reproduce

1. nvim

### Expected behavior

Detection of neovim status under Discord "Registered Games" in User Settings.

### Actual behavior

An error ocurrs upon neovim start up:
![image](https://github.com/user-attachments/assets/ae847188-2912-44df-953c-a31b1309cb39)

and no reflection of status in Discord:
![image](https://github.com/user-attachments/assets/8ed53c63-4127-4418-8815-1f4dd100b11d)

### Minimal configuration

```Lua
return
{
  {
    'vyfor/cord.nvim',
    branch = 'client-server',
    build = ':Cord fetch',
    event = "VeryLazy",
    opts = {}, -- calls require('cord').setup()
  },
}
```

**Comment by vyfor** [comment]
Hey, could you please try running `chmod +x ~/.local/share/nvim/cord/bin/cord` (assuming that's where nvim stores the data dir for you) and restart Neovim?

**Comment by me11203sci** [comment]
This worked after closing all instances of Neovim and restarting Discord. Apologies for the trouble.

**Comment by vyfor** [comment]
I've added the `chmod` call to the plugin, so this issue should no longer occur in future releases.
I assume your problem is resolved, so I'll go ahead and close this. If you run into any other issues, feel free to open a new one.
