### ISSUE TITLE
Add the shell icon to zshell files

### ISSUE THREAD

**Issue by PCesteban** [vyfor/cord.nvim#45]
### Description

Currently, the zshell type files has no icons (default txt icon is displayed), for example, the .zshrc file, I tried to put it manually via the assets config like this: 

```
  assets = {
    ['zsh'] = 'shell',
  },
```
But is not working as expected: 
![image](https://github.com/vyfor/cord.nvim/assets/48070832/40d6eb75-aa3e-4a81-a2e6-7216e8e616ab)

'zsh' is the type recognized by vim. Maybe I'm doing something wrong, but still, would be good to have it by default since zshell is widely used.

**Comment by vyfor** [comment]
In the current implementation, you must provide a full link to the icon (e.g., `https://raw.githubusercontent.com/vyfor/cord.nvim/master/assets/language/shell.png`), or it will be treated as a rich presence asset. I'll push a fix that should make it default to standard icons if no custom client ID is provided, hopefully resolving this issue and allowing such icon overrides. I'll also add `zsh` to the supported languages. Thanks!
