### ISSUE TITLE
Add Julia language

### ISSUE THREAD

**Issue by PCesteban** [vyfor/cord.nvim#51]
### Description

Would be good to add Julia's icon, it is a widely used scientific programming language.
https://julialang.org/

**Comment by vyfor** [comment]
I experimented with the colors but couldn't find a good one to put on the background, do you have anything in mind?
![image](https://github.com/vyfor/cord.nvim/assets/92883017/b25945d0-e87d-4eb9-8a4b-612e02c12dfc)
![image](https://github.com/vyfor/cord.nvim/assets/92883017/6b908ee6-1103-45d1-aac0-96524d5b7f97)
![image](https://github.com/vyfor/cord.nvim/assets/92883017/4933ecd8-f69e-4729-a897-ef4de07fb7a6)
![image](https://github.com/vyfor/cord.nvim/assets/92883017/38701e0e-cce6-4d2b-ad47-ed5b436da6af)

**Comment by PCesteban** [comment]
I actually think the first one is fine
