### ISSUE TITLE
feat: Support Git-related filetypes and plugins

### ISSUE THREAD

**Issue by vyfor** [vyfor/cord.nvim#55]
### Description

[File]
`gitattributes`, `gitconfig`, `gitsendemail`

[Git]
`gitcommit`, `gitrebase`
`fugitive`, `fugitiveblame`
`magit`
`git.nvim`
`lazygit`[^1]
`Neogit...`[^2]

These plugins have their own logos but will use the default Git icon due to the following reasons:
[^1]: No SVG / transparent variant found.
[^2]: Does not match with the existing [Git](https://github.com/vyfor/cord.nvim/blob/master/assets/language/git.png) icon design.

**Comment by PCesteban** [comment]
Hello @vyfor, I just updated the plugin, and but when I opened lazygit I'm still seeing this: 
![image](https://github.com/vyfor/cord.nvim/assets/48070832/6305e600-5700-46df-b1a1-10aa5c71dc50)

**Comment by vyfor** [comment]
Hey! Are you using the lazygit plugin?

**Comment by vyfor** [comment]
@PCesteban I believe you're opening lazygit through some kind of a terminal, which is not yet supported.

**Comment by PCesteban** [comment]
Ah, I'm using it via lunarvim. I'm not sure if lunarvim uses the plugin or something else, seems like it's calling the lazygit executable with toggleterm which is another plugin :/

**Comment by vyfor** [comment]
@PCesteban Hmm, I won't be at home for a few days so I cannot really look into it right now. Just open an issue and I'll tackle it once I'm back.

**Comment by PCesteban** [comment]
#57 done
