### ISSUE TITLE
Lunarvim lazygit dont show the git Icon

### ISSUE THREAD

**Issue by PCesteban** [vyfor/cord.nvim#57]
### Description

I use lazygit with lunarvim. I'm not sure how lunarvim handles lazygit, if through the plugin or something else, seems like it's calling the lazygit executable with toggleterm which is another plugin. 

![Screenshot from 2024-06-03 11-54-47](https://github.com/vyfor/cord.nvim/assets/48070832/c8f7861d-2956-4731-b40c-ff0637c6a41e)

The expected behaviour is to have the same icon as git filetypes: 
![Screenshot from 2024-06-03 11-59-32](https://github.com/vyfor/cord.nvim/assets/48070832/f2de9784-1f5e-4ebd-b5be-31a4d1a4ab69)

**Comment by vyfor** [comment]
Implemented in #64, thanks!
