### ISSUE TITLE
Toggle between language and logo as main image

### ISSUE THREAD

**Issue by redyf** [vyfor/cord.nvim#67]
### Description

For example, in [neocord](https://github.com/IogaMaster/neocord/) you can toggle between the editor logo and language.

### Additional information

![image](https://github.com/vyfor/cord.nvim/assets/98139059/0597d552-2c4a-4bf3-93e7-1fc297958bd1)
![image](https://github.com/vyfor/cord.nvim/assets/98139059/6c8d8c33-99a6-430f-b0e2-17416e187873)

**Comment by vyfor** [comment]
Implemented in #68. Thanks!
