### ISSUE TITLE
View Repository fails when repository cloned with ssh config label

### ISSUE THREAD

**Issue by Sveske-Juice** [vyfor/cord.nvim#77]
### Description

If the git repository contains a submodule, the 'View Repository' button redirects to the submodule's url instead of the projects repository.

### Operating system

Arch Linux

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

### Steps to reproduce

1. Create empty git repo
2. Add git submodule
3. Edit file in git repo
4. Press 'View Repository' and notice how it redirects to submodule's url

### Expected behavior

Expected to redirect to the projects git repository

### Minimal configuration

```Lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable',
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'vyfor/cord.nvim',
    build = './build',
    opts = {
        usercmds = true,
        log_level = nil,
        timer = {
          interval = 1500,
          reset_on_idle = false,
          reset_on_change = false,
        },
        editor = {
          image = nil,
          client = 'neovim',
          tooltip = 'The Superior Text Editor',
        },
        display = {
          show_time = true,
          show_repository = true,
          show_cursor_position = false,
          swap_fields = false,
          swap_icons = false,
          workspace_blacklist = {},
        },
        lsp = {
          show_problem_count = false,
          severity = 1,
          scope = 'workspace',
        },
        idle = {
          enable = true,
          show_status = true,
          timeout = 1800000,
          disable_on_focus = true,
          text = 'Idle',
          tooltip = '💤',
        },
        text = {
          viewing = 'Viewing {}',
          editing = 'Editing {}',
          file_browser = 'Browsing files in {}',
          plugin_manager = 'Managing plugins in {}',
          lsp_manager = 'Configuring LSP in {}',
          vcs = 'Committing changes in {}',
          workspace = 'In {}',
        },
        buttons = {
          {
            label = 'View Repository',
            url = 'git',
          },
        },
        assets = {},
    },
  },
}, {})
```

**Comment by Sveske-Juice** [comment]
Maybe it has something to do with the main project's repository being hosted on gitlab?

I observed this while developing on this git repository (on gitlab):
https://gitlab.com/Sveske-Juice/openbirch

So an easy way to reproduce this is just to clone that repo

**Comment by vyfor** [comment]
Hey! I cloned the repository with `git clone https://gitlab.com/Sveske-Juice/openbirch --recurse-submodules` but the button still redirects to the main repository as seen here:
![image](https://github.com/vyfor/cord.nvim/assets/92883017/fccb68b1-90d6-4e3c-8fcd-61d710cd797a)
![image](https://github.com/vyfor/cord.nvim/assets/92883017/739417e0-82c2-40e4-9a5c-cfff882340d6)

**Comment by vyfor** [comment]
Although, I noticed an additional url entry in the `.git/config` file:
![image](https://github.com/vyfor/cord.nvim/assets/92883017/0af550d6-eb07-4088-9c11-87d12fe9097a)

The plugin fetches the first url found in the config file, so I'd assume your submodule's url somehow ended up being listed first.

**Comment by vyfor** [comment]
Should be fixed in #78. Can you please confirm?

**Comment by Sveske-Juice** [comment]
On the latest commit, it seems to not properly detect that i am editing i git repository. The 'View Repository' button doesn't show up despite `show_repository = true` is set in the config.

 It does however work with every other git repository that I've tried, but just not the one mentioned on gitlab.

**Comment by Sveske-Juice** [comment]
I think i found the problem. I am using ~/.ssh/config to setup ssh keys for each remote:
```
Host gitlab
    Hostname gitlab.com
    User git
    Port 22
    IdentityFile ~/.ssh/redux-desk # the ssh key to use for gitlab.com
```
Which means that my `{workspace_path}/.git/config` looks like this:
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[submodule "doxygen-awesome-css"]
        active = true
        url = https://github.com/jothepro/doxygen-awesome-css.git
[remote "origin"]
        url = gitlab:Sveske-Juice/openbirch.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
        remote = origin
        merge = refs/heads/main
```
Notice that the `url` field doesn't start with "http" which means that it doesnt match in the call to [find_git_repository](https://github.com/vyfor/cord.nvim/blob/master/src/util/utils.rs#L312).

**Comment by vyfor** [comment]
I don't think I can address this issue since not everyone uses the same SSH configuration. Although, I can modify the function to fall back to the `git` command if `find_git_repository` fails. I created `find_git_repository` specifically to avoid relying on the `git` command, as it significantly affected the startup times.

**Comment by Sveske-Juice** [comment]
I see it's tedious problem. But i am not sure the git command would work because wouldn't it also just return the same?

When running `$ git remote get-url origin` it returns `gitlab:Sveske-Juice/openbirch.git` i.e whatever is defined in git config, which is not a url that can be used

**Comment by vyfor** [comment]
I'm not sure if this can be resolved without involving the SSH configuration. I'm open to suggestions, otherwise, I would probably close the issue.

**Comment by Sveske-Juice** [comment]
It would be quite complicated and involving mapping the git label to the remote host in the ssh config, which i don't think is worth the hassle of implementing
