### ISSUE TITLE
How to use the `editor` config?

### ISSUE THREAD

**Issue by daUnknownCoder** [vyfor/cord.nvim#83]
I am working on my own Neovim Distro, i have it in my `$NVIM_APPNAME` but idk how to use `editor.image` (i made a logo)? should i add a file location? [like `~/Downloads/img.png`?] coz i dont have it hosted online anywhere

if my `client` name is `NeutronVim` what should i keep in `editor.client`? [`NeutronVim` or `neutronvim` (as in readme)]

will `cord` be able to see-through things? like i open `nvim-tree` and it updates, i open `lazy` it updates, i open `telescope` it updates?

in this:
```lua
   {
     lazy = {                                 -- Vim filetype or file name or file extension = table or string
       name = 'Lazy',                         -- Optional override for the icon name, redundant for language types
       icon = 'https://example.com/lazy.png', -- Rich Presence asset name or URL
       tooltip = 'lazy.nvim',                 -- Text to display when hovering over the icon
       type = 2,
     },
     ['Cargo.toml'] = 'crates',
  },
```
so can i overcome the previous problem i had with jiriks's presence plugin (he forked over the unmaintained andweeb version)?: jiriks74/presence.nvim#44
```lua
        file_assets = {
          conf = { "Hyprland", "https://styles.redditmedia.com/t5_6sciw0/styles/communityIcon_h3cvittvupi91.png" },
        },
```

**Comment by vyfor** [comment]
Hello! Thanks for reaching out!

> if my `client` name is `NeutronVim` what should i keep in `editor.client`? [`NeutronVim` or `neutronvim` (as in readme)]

You will need to create a [Discord Application](https://discord.com/developers/applications). The rich presence's name is determined by the name of that application (Playing XYZ). You will then need to copy the application's ID and set `editor.client` to that ID.

> coz i dont have it (the image) hosted online anywhere

The image has to be hosted somewhere online. If you use a third-party hosting service, you can provide a direct URL to the icon in `editor.image`. Or, you can upload the image as an asset under your application's **Rich Presence** -> **Art Assets** section and simply provide the name of the asset. Do note that it may take a while for Discord to update its file cache.

And regarding the linked issue, I haven't used Hyprland personally, but from my research, the configuration file appears to be named as `hyprland.conf`. If this naming is consistent, you could configure it as follows:

```lua
editor = {
  image = 'https://...',
  client = '01234567890',
},
assets = {
  ['hyprland.conf'] = 'https://...',
  
  -- ['hyprland.conf'] = {
  --   icon = 'https://...',
  --   tooltip = 'Hyprland Config', -- Optionally set a tooltip
  -- },
},
```

I hope this helps! If you have any more questions, feel free to ask.

**Comment by daUnknownCoder** [comment]
> I haven't used Hyprland personally, but from my research, the configuration file appears to be named as `hyprland.conf`

It should be anything under the `~/.config/hypr` with `hypr*.conf`

**Comment by vyfor** [comment]
Hm, it seems that this would require an additional check for the entire path and a way to match against patterns, which Cord does not currently support, as it may introduce unwanted overhead and make the codebase a bit too complex. Are there any other common names for the config file besides `hyprland.conf` and `hypr.conf`? You could provide the same icon for each of them.

**Comment by daUnknownCoder** [comment]
like anything under `~/.config/hypr` falls under the jurisdiction of hyprland (theres also a treesitter grammer made only for hyprland (hyprland) -> an lsp is also in the works (hyprls)

**Comment by vyfor** [comment]
That requires iterating over the table until a match is found, which seems to be a performance bottleneck, given that it runs on each presence update. One thing we can do is introduce two new fields to the configuration, one, where you specify the directories to be searched and one for pattern matching. To avoid cluttering, I'd have them organized into one general field as follows:
```lua
assets = {
  ids = {}, -- regular assets are moved here
  dirs = {},
  patterns = {},
}
```
But that would be a breaking change to the configuration structure. I could inform the users in the commit's description, and/or support the old way of defining assets alongside the new way, although I'm not very fond of this idea. What do you think?

**Comment by daUnknownCoder** [comment]
i guess theres no need for breaking stuff...

![image](https://github.com/vyfor/cord.nvim/assets/84800625/e9cd5a73-8e3d-4c2a-9c20-322a58ef6417)

so vim.bo.filetype results in `hyprlang`

so this code snippet works for me:
```lua
      assets = {
        lazy = {
          name = "Lazy",
          icon = "https://avatars.githubusercontent.com/u/122150220?s=200&v=4",
          tooltip = "lazy.nvim",
          type = 2,
        },
        hyprlang = {
          name = "Hyprland",
          icon = "https://styles.redditmedia.com/t5_6sciw0/styles/communityIcon_h3cvittvupi91.png",
          tooltip = "Hyprland",
          type = 1,
        },
      },
```

**Comment by daUnknownCoder** [comment]
Heyo i found a bug... 🐞 

when doing `config.display.swap_icons = true`, the icons do switch but the tooltips dont
![2024-07-06-155912_hyprshot](https://github.com/vyfor/cord.nvim/assets/84800625/85bfa3e6-3557-4ceb-b930-e920184981cf)

it doesnt change from `lua` to `the superior text editor` or whatever the text was

**Comment by vyfor** [comment]
> i guess theres no need for breaking stuff...
I'll still have to implement those two in the near future, but we can put it off for the time being if the treesitter approach is working for you.

> when doing `config.display.swap_icons = true`, the icons do switch but the tooltips dont
Whoops, can confirm. Looks like I forgot to reassign the two. I'll push a fix asap.

**Comment by daUnknownCoder** [comment]
and yeah the buttons thing doesnt work
my config:
```lua
  {
    "vyfor/cord.nvim",
    build = "./build",
    event = "VeryLazy",
    opts = {
      display = {
        show_cursor_position = true,
        swap_icons = true,
      },
      editor = {
        image = "untitled_design_6_1_",
        client = "1258853126916800655",
      },
      lsp = {
        show_problem_count = true,
        scope = "buffer",
      },
      assets = {
        lazy = {
          name = "Lazy",
          icon = "https://avatars.githubusercontent.com/u/122150220?s=200&v=4",
          tooltip = "lazy.nvim",
          type = 2,
        },
        hyprlang = {
          name = "Hyprland",
          icon = "https://styles.redditmedia.com/t5_6sciw0/styles/communityIcon_h3cvittvupi91.png",
          tooltip = "Hyprland",
          type = 1,
        },
      },
      buttons = {
        {
          label = "View Repository",
          url = "git",
        },
      },
    },
  },
```

**Comment by vyfor** [comment]
If you've received the new UI update related to user profiles, I believe the issue lies within the Discord client itself, as I'm experiencing the same thing. Perhaps you could ask a friend to confirm whether the button appears for them.

**Comment by daUnknownCoder** [comment]
> If you've received the new UI update related to user profiles, I believe the issue lies within the Discord client itself, as I'm experiencing the same thing. Perhaps you could ask a friend to confirm whether the button appears for them.

none of my friends use linux 🫠, i am the lone wolf who overcome the adversity of linux cli, perhaps you can switch window managers? i only use hyprland so i have no other manager and the time it would take would be a waste

**Comment by vyfor** [comment]
No, what I mean is to ask someone on Discord to check whether you actually have the buttons on your Rich Presence, as this may be a bug on the client-side. If that does not help, try to replace `git` with the actual repository url, in case it fails to fetch it from the config.

**Comment by vyfor** [comment]
Pushed a fix to master. `config.display.swap_icons` should behave correctly now. Do you have any other questions?

**Comment by daUnknownCoder** [comment]
> Pushed a fix to master. `config.display.swap_icons` should behave correctly now. Do you have any other questions?

that was quick (it works)

**Comment by vyfor** [comment]
> i just launched discord on my browser and there's no sign of the button (i also tried switching accounts and accessing my account thru my alt which failed)

I'll be closing the issue as it turned out to be a bug on Discord's side. Feel free to open a new one if you have any other questions.
